# Categories for funders based on the provided list
FUNDER_CATEGORIES = {
    "Foundation": [
        "AARP Foundation", "Abrams Foundation Inc", "Alfred P. Sloan Foundation",
        "Allegis Group Foundation", "Allegis Group Foundation Inc", "Altman Foundation",
        "Amalgamated Charitable Foundation Inc", "American Endowment Foundation",
        "American Express Foundation", "American Heart Association", "American Idea Foundation Inc",
        "American Online Giving Foundation Inc", "American Student Assistance",
        "Amica Companies Foundation", "Amplify Her Foundation", "Anderman Family Foundation",
        "Ann Theodore Foundation", "Anna Carolina and Soo Kim Foundation",
        "Anna-Maria and Stephen Kellen Foundation",
        "Anna-Maria and Stephen Kellen Foundation Inc C/o Joel E Sammet & Co LLP",
        "Annie E. Casey Foundation", "Apex Foundation", "Apollo Opportunity Foundation",
        "Aps Foundation Inc", "Arakawa Foundation", "ARBOR BROTHERS INC", "Arbor Rising (Brothers)",
        "Ardian Us Foundation Inc", "Ares Charitable Foundation", "Ares Foundation",
        "Ares Management Foundation", "Arizona Community Foundation", "Arrow Impact",
        "Ascendium", "Ascendium Education", "Ascendium Education Group", "Ascension Health Alliance",
        "At&t Foundation", "Atlassian Foundation", "Aven Foundation", "Bain Capital Children's Charity Ltd",
        "Baird Foundation Inc", "Ballmer Group", "Baltimore Community Foundation",
        "Bank of America Charitable Foundation", "Barnabas Health Inc", "Barton Family Foundation",
        "Bd Foundation Inc", "Bell Charitable Foundation", "Bernard F & Alva B Gimbel Foundation Inc",
        "Beth and Ravenel Curry Foundation", "Betty and Davis Fitzgerald Foundation, Inc.",
        "Bezos Family Foundation", "Biella Foundation", "BILL & MELINDA GATES FOUNDATION",
        "Black Family Philanthropies", "Blue Meridian Partners Inc", "BNY Mellon Foundation",
        "Boone Family Foundation", "Booth Ferris Foundation", "Booz Allen Foundation",
        "Boston Bullpen Project Inc", "Brad and Danielle Tilden Family Foundation (c/o Kovark & Kim Pllc)",
        "Breyer Family Foundation", "Bright Funds Foundation", "Broadridge Foundation C/o Broadridge Financial Solutions",
        "Byrne Family Foundation Trust", "C D Spangler Foundation Inc", "California Community Foundation",
        "California Endowment", "California Physicians' Service Foundation DBA Blue Shield of California Foundation",
        "Carl B and Florence E King Foundation", "Carnegie Corporation of New York",
        "Carnegie Corporation of NY", "Carroll and Milton Petrie Foundation", "Carson Fam Charitable Trust",
        "Caterpillar Foundation", "Centene Foundation", "Charina Endowment Fund Inc",
        "Charities Aid Foundation of America", "Charles and Helen Schwab Foundation",
        "Charles Hayden Foundation", "Charles Koch Foundation", "Chavez Family Foundation",
        "Chicago Foundation for Women", "Chubb Charitable Foundation", "Circle of Service Foundation",
        "Citi Foundation", "Citizens Charitable Foundation", "Citizens Philanthropic Foundation Inc",
        "Citybridge Foundation", "Claneil Foundation", "Clark Charitable Foundation Inc DBA a James & Alice B Clark Foundation",
        "Clark Foundation", "Colonel Stanley R Mcneil Foundation", "Colorado Gives Foundation (formerly Community First Foundation)",
        "Columbus Foundation", "Combined Jewish Philanthropies of Greater Boston, Inc.",
        "Comic Relief Inc.", "Communities Foundation of Texas, Inc.", "Community Foundation for Greater Atlanta",
        "Community Foundation for Southeast Michigan", "Community Foundation of New Jersey",
        "Connelly Foundation", "Connolly Family Foundation Inc", "Conrad N Hilton Foundation",
        "Consumers Energy Foundation", "Craig Newmark Foundation", "Crankstart Foundation",
        "Credit Suisse Americas Foundation", "Cvs Health Foundation", "Dayton Foundation Plus Inc",
        "Delaware Community Foundation", "Dennis M Jones Family Foundation Formerly Dennis & Judith Jones Char Fd T",
        "Desai Sethi Foundation Inc", "Deutsche Bank Americas Foundation", "Diane and Bruce Halle Foundation",
        "Digital Harbor Foundation", "Disabled American Veterans Charitable Service Trust, Inc.",
        "Donald a Pels Charitable Trust Utd 8/18/92 C/o Pkf O'connor Davies", "Doran Family Foundation",
        "Dorot Foundation", "Draper Richards Kaplan Foundation", "Dw Gore Family Foundation",
        "E Schwartz Charitable Foundation", "E Schwartz Charitable Foundation Xxxxx7006",
        "East Bay Community Foundation", "Ecmc Foundation", "Ecw Giving Foundation Inc",
        "Edgerley Family Foundation", "Education Leaders of Color Inc", "Edward & Ellen Roche Relief Foundation",
        "Elastic", "Elbridge Stuart Foundation DBA Stuart Foundation", "Elizabeth Morse Genius Charitable Trust",
        "Emerson Charitable Trust", "Emerson Collective", "Emma G. Harris Foundation", "Endaoment",
        "Enterprise Community Partners Inc."
    ],
    "Corporate": [
        "Abbvie", "Accel", "Accenture", "Acorns", "Adobe", "ADP", "Aetna", "Akamai Foundation Inc",
        "AlleyCorp", "Allstate Foundation", "Alphadyne Asset Management", "Amazon", "American Express",
        "Anthropic", "Apollo", "Apollo Global Management", "Autodesk", "Bain Capital Ventures",
        "Bank of America", "Bank of America?", "Betterment", "Bezos Family Foundation", "Blackbaud",
        "Blackrock", "Blackstone", "Block (formerly Square)", "Block.one", "Bloomberg",
        "Bloomberg (Mike) Household", "Bloomingdale's", "BNY", "BNY Mellon", "Broadridge", "BSE Global",
        "Buffalo Sabres (NHL)", "Bumble", "Cameo", "capital one", "Capital Workforce Partners, Inc.",
        "Carlyle", "CBRE", "Centerview Partners", "Check Point Software", "Chime", "Chubb", "Cigna Health Insurance",
        "Citi", "Citizens Bank", "Citizens?", "ClassPass", "Cobbworks Inc", "Coca-Cola Foundation Inc.",
        "Cognizant", "College Board", "College Futures Foundation", "Comcast", "Con Edison", "ConEd",
        "ConEdison", "Cortex", "Costco", "CrowdStrike", "Darktrace", "Daves Killer Bread Foundation",
        "Deloitte", "Deutsche Bank", "Deutsche Bank?", "Docusign", "Dropbox", "EQT Partners",
        "Equitable Foundation Inc", "Ernst & Young (EY)", "Ernst & Young Foundation", "Etsy", "Expedia",
        "F5", "Fairfield County's Community Foundation", "Fidelity", "Fidelity Foundation", "Fifth Third Bank",
        "Finish Line Foundation", "Finnegan Family Foundation", "First Eagle Investments Foundation",
        "First Solar", "Fis Foundation Inc", "Fitzgerald (William) Household", "Flex Foundation (f/k/a Flextronics Foundation)",
        "Focusing Philanthropy", "Focusing Philanthropy Inc", "Ford Foundation", "Fortinet",
        "Foundation For The Carolinas", "Fox Rock Foundation C/o Robert T & Karen Hale Jr",
        "France-Merrick Foundation Inc", "Friese Foundation", "Gap Inc.", "Garcia Family Foundation Inc",
        "GEICO", "General Atlantic", "Geoffrey C Hughes Foundation Inc", "Gilead Foundation", "Gitlab Foundation",
        "Givengain Foundation USA", "GoDaddy", "GoFundMe.org", "Goldman Sachs", "Goldman Sachs Philanthropy Fund",
        "Goodnation Foundation", "Google", "Google.org", "Gray Foundation C/o the Ayco Company Lp",
        "Greater Cincinnati Foundation", "GREATER TEXAS FOUNDATION", "Greater Washington Community Foundation",
        "Greenbridge Family Foundation", "Greenlight Fund Inc.", "Gucci", "Gula Tech Foundation Inc",
        "Hagedorn Fund", "Handshake", "Harbor Fund", "Hard Rock", "Harman Family Foundation C/o Dressler Associates",
        "Harry and Jeanette Weinberg Foundation", "Hasbro Foundation Inc", "Hearst", "Hearst Foundation",
        "Hearst Foundations", "Hearthland Foundation", "Heckscher Foundation", "Helen Pumphrey Denit Charitable Trust",
        "Heron Foundation", "Highland Partners Charitable Fund", "Hillman Family Foundations", "Hilton Foundation",
        "Hinge", "Hispanic Federation", "Hopper-Dean Foundation C/o Catalyst Family Office LLC",
        "Houston Endowment Inc", "HSBC", "Hsjk Foundation Inc", "IBM International Foundation", "Iconiq",
        "Imaginable Futures", "Imc Chicago Charitable Foundation", "ImpactAssets",
        "Incyte Charitable Giving Foundation", "Ingram-White Castle Foundation", "Inherent Foundation",
        "Insight Partners", "Intel", "International Rescue Committee, Inc.", "Intuit", "Ira DeCamp Foundation",
        "Ira W. De Camp Foundation", "J B Fuqua Foundation Inc", "Jain Family Institute (JFI)",
        "James and Judith K. Dimon Foundation", "James J Pallotta Charitable Trust", "Janey Fund Charitable Trust",
        "JetBlue", "JetBrains Foundation", "Jewish Communal Fund", "Jewish Community Federation of San Francisco the Peninsula Marin & Sonoma",
        "Jobs For The Future Inc", "Jobsfirstnyc", "John and Marcia Goldman Foundation",
        "John S. and James L. Knight Foundation, Inc.", "Joseph B Whitehead Foundation", "JPMorgan Chase (JPMC)",
        "Jpmorgan Chase Foundation", "Kaiser Foundation Health Plan of Georgiainc",
        "Kaiser Foundation Health Plan of the Mid-Atlantic States Inc", "Kaphan Foundation", "Kapor Capital",
        "Karin Bain and John Kukral Foundation", "Kate Spade New York Foundation", "Key Lime Foundation",
        "Kingsbury Road Charitable Foundation", "KKR", "Kla Foundation", "KnowledgeWorks Foundation",
        "Koret Foundation", "KPMG U.S. Foundation, Inc.", "KPMG US", "L&l Foundation", "Laura and John Arnold Foundation",
        "Lawrence Foundation", "Lego Community Fund US Inc", "Leon Lowenstein Foundation Inc",
        "Leslie Family Foundation", "Liberty Mutual Foundation", "Life Science Cares, Inc.",
        "Lincoln Financial Foundation Inc", "Linde Family Foundation C/o Eric Riak - Cibc Private Wealth Mgmt",
        "Link Logistics", "LinkedIn", "LISC", "Llewellyn Family Foundation", "Lloyd a Fry Foundation",
        "Local Initiatives Support Corp.", "Loeb Charitable Foundation", "London Stock Exchange Group",
        "Lone Pine Foundation", "Lone Pine Foundation Inc", "Long Island Ducks", "LOreal",
        "Louis and Anne Abrons Foundation Inc", "Lukaj Foundation Inc C/o Bank Street", "Lululemon",
        "Lumina Foundation", "Lumina Foundation for Education Inc", "M&T Bank", "M&t Charitable Foundation",
        "MacArthur Foundation", "Macquarie", "Margaret a Meyer Family Foundation Inc", "Marguerite Casey Foundation",
        "Marin Community Foundation", "Mastercard", "Mathis Pfohl Foundation", "Maverick Capital Foundation",
        "May and Stanley Smith Charitable Trust", "Mayer and Morris Kaplan Foundation", "Meadows Foundation Inc",
        "Medina Foundation", "Mellen Charitable Foundation (fka Tf Fdn) C/o Paul Mccoy Family Office Services",
        "Memorial Sloan Kettering Cancer Center", "Merck", "Meta (formerly Facebook)", "Metlife Foundation",
        "Michael & Susan Dell Foundation", "Michelson Medical Research Foundation Inc", "Michelson Philanthropies Inc",
        "Microsoft", "Milstein (Michael) Household", "Mission 44", "Missouri Children's Trust Fund",
        "Mizuho", "Mizuho Americas", "Moccasin Lake Foundation", "Moderna Charitable Foundation", "Moody's",
        "Morgan Stanley", "Morgan Stanley Global Impact Funding Trust Inc", "Morningstar",
        "Mother Cabrini Health Foundation", "Motorola Solutions Foundation", "Mozilla Foundation",
        "Mussafer Family Foundation", "NaHCO3 (Sodium Bicarbonate)", "National Basketball Association Foundation",
        "National Football League", "National Grid Foundation", "National Philanthropic Trust",
        "National Science Foundation", "National Telecommunication & Information Administration (NTIA)",
        "NBA Foundation", "NCR Corporation", "Ncr Foundation", "NEO Philanthropy", "NEW AMERICA FOUNDATION",
        "New Hampshire Charitable Foundation", "New Profit", "New York City Council",
        "New York City Council District 02 - Carlina Rivera", "New York City Council District 04 - Keith Powers",
        "New York City Council District 05 - Julie Menin", "New York City Council District 06 - Gale Brewer",
        "New York City Council District 08 - Diana Ayala", "New York City Council District 12 - Kevin Riley",
        "New York City Council District 17 - Rafael Salamanca Jr.", "New York City Council District 18 - Amanda Farias",
        "New York City Council District 21 - Francisco Moya", "New York City Council District 23 - Linda Lee",
        "New York City Council District 25 - Shekar Krishnan", "New York City Council District 26 - Julie Won",
        "New York City Council District 27 - Nantasha Williams", "New York City Council District 28 - Adrienne Adams",
        "New York City Council District 29 - Lynn Schulman", "New York City Council District 30 - Robert Holden",
        "New York City Council District 34 - Jennifer Gutiérrez", "New York City Council District 44",
        "New York City Council District 47 - Justin Brannan", "New York City Council District 51 - Joseph Borelli",
        "New York City Economic Development Corporation", "New York City FC (MLS)", "New York Community Trust",
        "New York Community Trust aka Community Funds, Inc.", "New York Jets (NFL)", "New York Knicks",
        "New York Rangers (NHL)", "New York Red Bulls (MLS)", "New York Times", "New York Yankees",
        "NextEra Energy", "Nick & Michele Keller Family Foundation", "Nielsen", "Nike",
        "Nina Mason Pulliam Charitable Trust", "Nordstrom", "Nvidia", "NYC Workforce Funders", "NYCT"
    ],
    "Government": [
        "Empire State Development", "NYS Assembly District 12 - Michael Gianaris", 
        "NYS Assembly District 13 - Jessica Ramos", "NYS Assembly District 14 - Leroy Comrie"
    ]
}
