[theme]
# Pursuit brand color - blue/purple (#4B46E9)
primaryColor = "#4B46E9"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
address = "0.0.0.0"
port = 5000